console.log(2);
try {
	let a = 0 / 0;
	console.log(a);
} catch (error) {
	console.log("Error ");
}
console.log(1);
